package live.mufin.skyblock.playerdata;

import live.mufin.skyblock.Main;

public class Stats {

	

	public enum Stat {
		DAMAGE, HEALTH, DEFENSE, TRUE_DEFENSE, STRENGTH, SPEED, CRIT_CHANCE, CRIT_DMG, INTELLIGENCE, MINING_SPEED,
		SEACREATURESPAWNRATE, MAGICFIND, PETLUCK, ABILITYDAMAGE, FEROCITY, MINING_FORTUNE, FARMING_FORTUNE,
		FORAGING_FORTUNE
	}
	
	
	

}
